import{S as l,N as a,K as d}from"./assets/vendor-c2c4a160.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();document.querySelector(".swiper-button-prev");document.querySelector(".swiper-button-next");const c=document.querySelector(".reviews-list");function u(){return fetch("https://portfolio-js.b.goit.study/api/reviews").then(t=>{if(!t.ok)throw new Error("Not found");return t.json()})}function m(t){const i=t.reduce((s,r)=>s+=`<li class="reviews-item swiper-slide"> <div class="swiper-item-wrap">
    <p class="reviews-item-text">${r.review}</p>
    <div class="reviews-item-wrap">
    <img src="${r.avatar_url}" alt="${r.author}" class="reviews-item-img">
    <h3 class="reviews-item-title">${r.author}</h3>
    </div>
    </div>
    </li>`,"");c.insertAdjacentHTML("beforeend",i)}function f(){new l(".mySwiper",{speed:400,spaceBetween:100,modules:[a,d],keyboard:{enabled:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}}),u().then(t=>{m(t)}).catch(t=>{alert("Error: "+t.message),c.innerHTML="<li class='reviews-item'><span class='not-found'>Not found<span></li>"})}function p(){const t=document.getElementById("toggleSwitch"),i=document.querySelectorAll(".header-link"),s=document.querySelector(".header-logo");t.addEventListener("click",function(){this.checked?(document.body.classList.add("dark-mode"),i.forEach(r=>{r.classList.add("black-theme-link")}),s.classList.add("black-theme-logo")):(document.body.classList.remove("dark-mode"),s.classList.remove("black-theme-logo"),i.forEach(r=>{r.classList.remove("black-theme-link")}))})}p();f();
//# sourceMappingURL=commonHelpers.js.map
